#!/usr/bin/env Rscript
# Systematic testing of DINA model asymptotic behavior
# This script tests all datasets generated by the data generation script

cat("\n")
cat("╔════════════════════════════════════════════════════════════════╗\n")
cat("║  Systematic DINA Model Asymptotic Behavior Testing            ║\n")
cat("╚════════════════════════════════════════════════════════════════╝\n\n")

# Setup ====================================================================
rm(list = ls())
pkg <- c("ggdmc", "ggdmcPrior", "ggdmcModel", "cdModel")
pkg_ok <- sapply(pkg, require, character.only = TRUE)

if (!all(pkg_ok)) {
  stop("Failed to load required packages: ", names(pkg_ok)[!pkg_ok])
}

home_dir <- "/media/yslin/Tui/01_Projects/ggdmc/tests/testthat"

# Define all dataset sample sizes
# sample_sizes <- c(100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000)
# sample_sizes <- c(100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000)
sample_sizes <- c(100, 200, 500, 1000, 2000, 5000)


# Create results directory if it doesn't exist
results_dir <- file.path(home_dir, "Group10_cdm_subjects/results")
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
  cat("Created results directory:", results_dir, "\n\n")
}

# Sampling parameters (adjust as needed)
SAMPLING_CONFIG <- list(
  nmc = 100, # Number of iterations
  nchain = NULL, # Number of chains
  migration_prob = 0.05, # Migration probability for first stage
  thin_stage1 = 8, # Thinning for first stage
  thin_stage2 = 4, # Thinning for second stage
  is_pblocked = FALSE, # Blocked sampling
  seed = 9032, # Random seed
  ncore = 3 # Number of cores (change based on available)
)

# Storage for all results
all_results <- list()
# n <- sample_sizes[1]
# Main Testing Loop ========================================================
for (n in sample_sizes) {
  cat("\n")
  cat("════════════════════════════════════════════════════════════════\n")
  cat(sprintf("  Testing N = %d\n", n))
  cat("════════════════════════════════════════════════════════════════\n\n")

  # Construct file paths
  data_file <- sprintf("subject_dina0_N%06d.rda", n)
  data_path <- file.path(home_dir, "Group9_gen_cdm/data", data_file)
  save_file <- sprintf("fit_dina0_N%06d.rda", n)
  save_path <- file.path(results_dir, save_file)

  # Check if data file exists
  if (!file.exists(data_path)) {
    cat("⚠ WARNING: Data file not found:", data_path, "\n")
    cat("  Skipping N =", n, "\n")
    next
  }

  cat("Loading data from:", data_path, "\n")

  # Load the data
  load(data_path)
  cat("✓ Data loaded successfully\n\n")

  # Stage 1: Initial sampling with migration
  cat("Stage 1: Initial sampling (migration =", SAMPLING_CONFIG$migration_prob, ")\n")
  fits0 <- StartSampling_subject(
    sub_dmis[[1]], sub_priors,
    ncore = SAMPLING_CONFIG$ncore,
    nmc = SAMPLING_CONFIG$nmc,
    nchain = SAMPLING_CONFIG$nchain,
    sub_migration_prob = SAMPLING_CONFIG$migration_prob,
    thin = SAMPLING_CONFIG$thin_stage1,
    is_pblocked = SAMPLING_CONFIG$is_pblocked,
    seed = SAMPLING_CONFIG$seed
  )


  # Stage 2: Restart sampling without migration
  cat("Stage 2: Restart sampling (migration = 0.00)\n")
  fits1 <- ggdmc:::RestartSampling_subject(
    fits0,
    sub_migration_prob = 0.00,
    thin = SAMPLING_CONFIG$thin_stage2,
    is_pblocked = SAMPLING_CONFIG$is_pblocked,
    seed = SAMPLING_CONFIG$seed
  )

  # Use final fits
  fits <- fits1

  # Diagnostics ===========================================================
  cat("Computing diagnostics...\n")

  # Rebuild posterior from all chains
  fit <- RebuildPosterior(fits)

  # Compute Gelman-Rubin statistics
  hat_overall <- gelman(fit)
  cat(sprintf("  Overall MPSRF = %.4f\n", hat_overall$mpsrf))

  # Per-chain diagnostics
  chain_mpsrf <- numeric(SAMPLING_CONFIG$ncore)
  for (i in seq_len(SAMPLING_CONFIG$ncore)) {
    hat_chain <- gelman(fits[[i]])
    chain_mpsrf[i] <- hat_chain$mpsrf
    cat(sprintf("  Chain %d MPSRF = %.4f\n", i, hat_chain$mpsrf))
  }

  # Parameter Estimation ==================================================
  cat("\nParameter estimation:\n")
  options(digits = 4)

  # Compare estimates to true values
  est_theta <- ggdmc::compare(fit, ps = true_vector)

  # Calculate summary statistics
  median_estimates <- est_theta["50 Estimate", ]
  true_values <- est_theta["True", ]
  bias <- est_theta["Median-True", ]
  median_absolute_error <- abs(bias)

  cat("\nBias (Median - True):\n")
  print(bias)

  cat("\nMedian Absolute Error:\n")
  print(median_absolute_error)

  # Store results =========================================================
  result_summary <- list(
    n = n,
    data_path = data_path,
    sampling_config = SAMPLING_CONFIG,
    diagnostics = list(
      overall_mpsrf = hat_overall$mpsrf,
      chain_mpsrf = chain_mpsrf,
      convergence = hat_overall$mpsrf < 1.1
    ),
    estimates = list(
      comparison_table = est_theta,
      median_estimates = median_estimates,
      true_values = true_values,
      bias = bias,
      mae = median_absolute_error,
      mean_mae = mean(median_absolute_error)
    ),
    fits = list(
      fits0 = fits0,
      fits1 = fits1
    )
  )

  all_results[[as.character(n)]] <- result_summary

  # Save individual result
  cat("\nSaving results to:", save_path, "\n")
  save(fits0, fits1, result_summary, file = save_path)
  cat("✓ Results saved\n")

  # Clean up to save memory
  rm(fits0, fits1, fits, fit, sub_dmis, sub_priors)
  gc()
}

# Summary Report ===========================================================
cat("\n\n")
cat("╔════════════════════════════════════════════════════════════════╗\n")
cat("║                    SUMMARY REPORT                              ║\n")
cat("╚════════════════════════════════════════════════════════════════╝\n\n")

if (length(all_results) == 0) {
  cat("⚠ No results to summarize\n")
} else {
  # Create summary table
  summary_table <- data.frame(
    Overall_MPSRF = numeric(),
    Converged = logical(),
    Mean_MAE = numeric(),
    stringsAsFactors = FALSE
  )

  for (res_name in names(all_results)) {
    res <- all_results[[res_name]]
    summary_table <- rbind(summary_table, data.frame(
      N = res$n,
      Overall_MPSRF = res$diagnostics$overall_mpsrf,
      Converged = res$diagnostics$convergence,
      Mean_MAE = res$estimates$mean_mae,
      stringsAsFactors = FALSE
    ))
  }

  cat("Overall Summary:\n")
  print(summary_table)

  # Convergence summary
  cat("\n\nConvergence Summary:\n")
  cat(sprintf("  Total datasets tested: %d\n", nrow(summary_table)))
  cat(sprintf(
    "  Converged (MPSRF < 1.1): %d\n",
    sum(summary_table$Converged)
  ))
  cat(sprintf(
    "  Not converged: %d\n",
    sum(!summary_table$Converged)
  ))

  # Asymptotic behavior
  cat("\n\nAsymptotic Behavior (Mean Absolute Error):\n")
  cat("  N       Mean MAE\n")
  cat("  ------  ---------\n")
  for (i in 1:nrow(summary_table)) {
    cat(sprintf(
      "  %6d  %.6f\n",
      summary_table$N[i],
      summary_table$Mean_MAE[i]
    ))
  }

  if (nrow(summary_table) > 1) {
    cat(
      "\n  → MAE decreases with N: ",
      ifelse(cor(summary_table$N, summary_table$Mean_MAE) < 0,
        "YES ✓", "NO ✗"
      ), "\n"
    )
  }

  # Save overall summary
  summary_path <- file.path(results_dir, "systematic_test_summary.rda")
  cat("\nSaving overall summary to:", summary_path, "\n")
  save(all_results, summary_table, SAMPLING_CONFIG, file = summary_path)

  # Create CSV for easy viewing
  csv_path <- file.path(results_dir, "systematic_test_summary.csv")
  write.csv(summary_table, csv_path, row.names = FALSE)
  cat("✓ Summary CSV saved to:", csv_path, "\n")
}

cat("\n")
cat("╔════════════════════════════════════════════════════════════════╗\n")
cat("║              ALL TESTS COMPLETED SUCCESSFULLY                  ║\n")
cat("╚════════════════════════════════════════════════════════════════╝\n\n")

cat("Results saved in:", results_dir, "\n\n")
