// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dcircle
arma::vec dcircle(arma::vec RT, arma::vec A, arma::vec P, double tmax, unsigned int kmax, unsigned int sz, unsigned int nw);
RcppExport SEXP _ggdmc_dcircle(SEXP RTSEXP, SEXP ASEXP, SEXP PSEXP, SEXP tmaxSEXP, SEXP kmaxSEXP, SEXP szSEXP, SEXP nwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type RT(RTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type sz(szSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nw(nwSEXP);
    rcpp_result_gen = Rcpp::wrap(dcircle(RT, A, P, tmax, kmax, sz, nw));
    return rcpp_result_gen;
END_RCPP
}
// dcircle300
Rcpp::List dcircle300(arma::vec P, double tmax, unsigned int kmax, unsigned int sz, unsigned int nw);
RcppExport SEXP _ggdmc_dcircle300(SEXP PSEXP, SEXP tmaxSEXP, SEXP kmaxSEXP, SEXP szSEXP, SEXP nwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type sz(szSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nw(nwSEXP);
    rcpp_result_gen = Rcpp::wrap(dcircle300(P, tmax, kmax, sz, nw));
    return rcpp_result_gen;
END_RCPP
}
// rcircle
arma::mat rcircle(unsigned int n, arma::vec P, double tmax, double h, unsigned int nw);
RcppExport SEXP _ggdmc_rcircle(SEXP nSEXP, SEXP PSEXP, SEXP tmaxSEXP, SEXP hSEXP, SEXP nwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nw(nwSEXP);
    rcpp_result_gen = Rcpp::wrap(rcircle(n, P, tmax, h, nw));
    return rcpp_result_gen;
END_RCPP
}
// rcircle_process
Rcpp::List rcircle_process(arma::vec P, double tmax, double h);
RcppExport SEXP _ggdmc_rcircle_process(SEXP PSEXP, SEXP tmaxSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(rcircle_process(P, tmax, h));
    return rcpp_result_gen;
END_RCPP
}
// r1d
Rcpp::List r1d(arma::vec P, double tmax, double h);
RcppExport SEXP _ggdmc_r1d(SEXP PSEXP, SEXP tmaxSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(r1d(P, tmax, h));
    return rcpp_result_gen;
END_RCPP
}
// likelihood
std::vector<double> likelihood(arma::vec pvector, S4 data, double min_lik, double precision);
RcppExport SEXP _ggdmc_likelihood(SEXP pvectorSEXP, SEXP dataSEXP, SEXP min_likSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pvector(pvectorSEXP);
    Rcpp::traits::input_parameter< S4 >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type min_lik(min_likSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood(pvector, data, min_lik, precision));
    return rcpp_result_gen;
END_RCPP
}
// p_df
arma::mat p_df(arma::vec pvector, std::string cell, std::string mtype, std::vector<std::string> pnames, std::vector<std::string> parnames, std::vector<std::string> dim0, std::vector<std::string> dim1, std::vector<std::string> dim2, std::vector<double> allpar, arma::ucube model, arma::uvec isr1, arma::umat n1idx, bool n1order);
RcppExport SEXP _ggdmc_p_df(SEXP pvectorSEXP, SEXP cellSEXP, SEXP mtypeSEXP, SEXP pnamesSEXP, SEXP parnamesSEXP, SEXP dim0SEXP, SEXP dim1SEXP, SEXP dim2SEXP, SEXP allparSEXP, SEXP modelSEXP, SEXP isr1SEXP, SEXP n1idxSEXP, SEXP n1orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pvector(pvectorSEXP);
    Rcpp::traits::input_parameter< std::string >::type cell(cellSEXP);
    Rcpp::traits::input_parameter< std::string >::type mtype(mtypeSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type pnames(pnamesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type parnames(parnamesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dim0(dim0SEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dim1(dim1SEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dim2(dim2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type allpar(allparSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type isr1(isr1SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type n1idx(n1idxSEXP);
    Rcpp::traits::input_parameter< bool >::type n1order(n1orderSEXP);
    rcpp_result_gen = Rcpp::wrap(p_df(pvector, cell, mtype, pnames, parnames, dim0, dim1, dim2, allpar, model, isr1, n1idx, n1order));
    return rcpp_result_gen;
END_RCPP
}
// ac_
arma::vec ac_(arma::vec x, unsigned int nlag);
RcppExport SEXP _ggdmc_ac_(SEXP xSEXP, SEXP nlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nlag(nlagSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_(x, nlag));
    return rcpp_result_gen;
END_RCPP
}
// trial_loglik
arma::cube trial_loglik(S4 samples, unsigned int thin_pointwise);
RcppExport SEXP _ggdmc_trial_loglik(SEXP samplesSEXP, SEXP thin_pointwiseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin_pointwise(thin_pointwiseSEXP);
    rcpp_result_gen = Rcpp::wrap(trial_loglik(samples, thin_pointwise));
    return rcpp_result_gen;
END_RCPP
}
// r_fastdm
Rcpp::List r_fastdm(unsigned int num_values, std::vector<double> params, double precision, bool stop_on_error);
RcppExport SEXP _ggdmc_r_fastdm(SEXP num_valuesSEXP, SEXP paramsSEXP, SEXP precisionSEXP, SEXP stop_on_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type num_values(num_valuesSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< bool >::type stop_on_error(stop_on_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(r_fastdm(num_values, params, precision, stop_on_error));
    return rcpp_result_gen;
END_RCPP
}
// p_fastdm
std::vector<double> p_fastdm(std::vector<double> rts, std::vector<double> params, double precision, int boundary, bool stop_on_error);
RcppExport SEXP _ggdmc_p_fastdm(SEXP rtsSEXP, SEXP paramsSEXP, SEXP precisionSEXP, SEXP boundarySEXP, SEXP stop_on_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< int >::type boundary(boundarySEXP);
    Rcpp::traits::input_parameter< bool >::type stop_on_error(stop_on_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(p_fastdm(rts, params, precision, boundary, stop_on_error));
    return rcpp_result_gen;
END_RCPP
}
// prd
std::vector<double> prd(std::vector<double> rts, std::vector<double> params, double precision, unsigned int b);
RcppExport SEXP _ggdmc_prd(SEXP rtsSEXP, SEXP paramsSEXP, SEXP precisionSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(prd(rts, params, precision, b));
    return rcpp_result_gen;
END_RCPP
}
// init_new
S4 init_new(S4 dmi, S4 prior, unsigned int nchain, unsigned int nmc, unsigned int thin, unsigned int report, double rp, double gammamult, double pm, double pm_old, bool block);
RcppExport SEXP _ggdmc_init_new(SEXP dmiSEXP, SEXP priorSEXP, SEXP nchainSEXP, SEXP nmcSEXP, SEXP thinSEXP, SEXP reportSEXP, SEXP rpSEXP, SEXP gammamultSEXP, SEXP pmSEXP, SEXP pm_oldSEXP, SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type dmi(dmiSEXP);
    Rcpp::traits::input_parameter< S4 >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nchain(nchainSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nmc(nmcSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type report(reportSEXP);
    Rcpp::traits::input_parameter< double >::type rp(rpSEXP);
    Rcpp::traits::input_parameter< double >::type gammamult(gammamultSEXP);
    Rcpp::traits::input_parameter< double >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< double >::type pm_old(pm_oldSEXP);
    Rcpp::traits::input_parameter< bool >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(init_new(dmi, prior, nchain, nmc, thin, report, rp, gammamult, pm, pm_old, block));
    return rcpp_result_gen;
END_RCPP
}
// init_old
S4 init_old(S4 samples, unsigned int nmc, unsigned int thin, unsigned int report, double rp, double gammamult, double pm, double pm_old, bool block, bool add);
RcppExport SEXP _ggdmc_init_old(SEXP samplesSEXP, SEXP nmcSEXP, SEXP thinSEXP, SEXP reportSEXP, SEXP rpSEXP, SEXP gammamultSEXP, SEXP pmSEXP, SEXP pm_oldSEXP, SEXP blockSEXP, SEXP addSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nmc(nmcSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type report(reportSEXP);
    Rcpp::traits::input_parameter< double >::type rp(rpSEXP);
    Rcpp::traits::input_parameter< double >::type gammamult(gammamultSEXP);
    Rcpp::traits::input_parameter< double >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< double >::type pm_old(pm_oldSEXP);
    Rcpp::traits::input_parameter< bool >::type block(blockSEXP);
    Rcpp::traits::input_parameter< bool >::type add(addSEXP);
    rcpp_result_gen = Rcpp::wrap(init_old(samples, nmc, thin, report, rp, gammamult, pm, pm_old, block, add));
    return rcpp_result_gen;
END_RCPP
}
// init_newhier
S4 init_newhier(S4 prior, S4 lprior, S4 sprior, List dmi, unsigned int nchain, unsigned int nmc, unsigned int thin, unsigned int report, double rp, double gammamult, double pm, double pm_old, bool block);
RcppExport SEXP _ggdmc_init_newhier(SEXP priorSEXP, SEXP lpriorSEXP, SEXP spriorSEXP, SEXP dmiSEXP, SEXP nchainSEXP, SEXP nmcSEXP, SEXP thinSEXP, SEXP reportSEXP, SEXP rpSEXP, SEXP gammamultSEXP, SEXP pmSEXP, SEXP pm_oldSEXP, SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< S4 >::type lprior(lpriorSEXP);
    Rcpp::traits::input_parameter< S4 >::type sprior(spriorSEXP);
    Rcpp::traits::input_parameter< List >::type dmi(dmiSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nchain(nchainSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nmc(nmcSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type report(reportSEXP);
    Rcpp::traits::input_parameter< double >::type rp(rpSEXP);
    Rcpp::traits::input_parameter< double >::type gammamult(gammamultSEXP);
    Rcpp::traits::input_parameter< double >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< double >::type pm_old(pm_oldSEXP);
    Rcpp::traits::input_parameter< bool >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(init_newhier(prior, lprior, sprior, dmi, nchain, nmc, thin, report, rp, gammamult, pm, pm_old, block));
    return rcpp_result_gen;
END_RCPP
}
// init_oldhier
S4 init_oldhier(S4 samples, unsigned int nmc, unsigned int thin, unsigned int report, double rp, double gammamult, double pm, double pm_old, bool block, bool add);
RcppExport SEXP _ggdmc_init_oldhier(SEXP samplesSEXP, SEXP nmcSEXP, SEXP thinSEXP, SEXP reportSEXP, SEXP rpSEXP, SEXP gammamultSEXP, SEXP pmSEXP, SEXP pm_oldSEXP, SEXP blockSEXP, SEXP addSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nmc(nmcSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type report(reportSEXP);
    Rcpp::traits::input_parameter< double >::type rp(rpSEXP);
    Rcpp::traits::input_parameter< double >::type gammamult(gammamultSEXP);
    Rcpp::traits::input_parameter< double >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< double >::type pm_old(pm_oldSEXP);
    Rcpp::traits::input_parameter< bool >::type block(blockSEXP);
    Rcpp::traits::input_parameter< bool >::type add(addSEXP);
    rcpp_result_gen = Rcpp::wrap(init_oldhier(samples, nmc, thin, report, rp, gammamult, pm, pm_old, block, add));
    return rcpp_result_gen;
END_RCPP
}
// rlba_norm
arma::mat rlba_norm(unsigned int n, arma::vec A, arma::vec b, arma::vec mean_v, arma::vec sd_v, arma::vec t0, arma::vec st0, bool posdrift);
RcppExport SEXP _ggdmc_rlba_norm(SEXP nSEXP, SEXP ASEXP, SEXP bSEXP, SEXP mean_vSEXP, SEXP sd_vSEXP, SEXP t0SEXP, SEXP st0SEXP, SEXP posdriftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_v(mean_vSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sd_v(sd_vSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type st0(st0SEXP);
    Rcpp::traits::input_parameter< bool >::type posdrift(posdriftSEXP);
    rcpp_result_gen = Rcpp::wrap(rlba_norm(n, A, b, mean_v, sd_v, t0, st0, posdrift));
    return rcpp_result_gen;
END_RCPP
}
// rprior_mat
NumericMatrix rprior_mat(S4 prior, unsigned int n);
RcppExport SEXP _ggdmc_rprior_mat(SEXP priorSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rprior_mat(prior, n));
    return rcpp_result_gen;
END_RCPP
}
// test_sumlogprior
double test_sumlogprior(arma::vec pvec, List prior);
RcppExport SEXP _ggdmc_test_sumlogprior(SEXP pvecSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pvec(pvecSEXP);
    Rcpp::traits::input_parameter< List >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(test_sumlogprior(pvec, prior));
    return rcpp_result_gen;
END_RCPP
}
// test_dprior
arma::vec test_dprior(arma::vec pvec, List prior);
RcppExport SEXP _ggdmc_test_dprior(SEXP pvecSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pvec(pvecSEXP);
    Rcpp::traits::input_parameter< List >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(test_dprior(pvec, prior));
    return rcpp_result_gen;
END_RCPP
}
// spdf
arma::vec spdf(arma::vec x, arma::vec RT, int n, double h_in, bool debug);
RcppExport SEXP _ggdmc_spdf(SEXP xSEXP, SEXP RTSEXP, SEXP nSEXP, SEXP h_inSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type RT(RTSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type h_in(h_inSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(spdf(x, RT, n, h_in, debug));
    return rcpp_result_gen;
END_RCPP
}
// dtnorm
std::vector<double> dtnorm(std::vector<double> x, double p1, double p2, double lower, double upper, bool lg);
RcppExport SEXP _ggdmc_dtnorm(SEXP xSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP lgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< bool >::type lg(lgSEXP);
    rcpp_result_gen = Rcpp::wrap(dtnorm(x, p1, p2, lower, upper, lg));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm
std::vector<double> rtnorm(unsigned int n, double p1, double p2, double lower, double upper);
RcppExport SEXP _ggdmc_rtnorm(SEXP nSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm(n, p1, p2, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// ptnorm
std::vector<double> ptnorm(std::vector<double> q, double p1, double p2, double lower, double upper, bool lt, bool lg);
RcppExport SEXP _ggdmc_ptnorm(SEXP qSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP ltSEXP, SEXP lgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< bool >::type lt(ltSEXP);
    Rcpp::traits::input_parameter< bool >::type lg(lgSEXP);
    rcpp_result_gen = Rcpp::wrap(ptnorm(q, p1, p2, lower, upper, lt, lg));
    return rcpp_result_gen;
END_RCPP
}
// rvonmises
arma::vec rvonmises(unsigned int n, double mu, double kappa);
RcppExport SEXP _ggdmc_rvonmises(SEXP nSEXP, SEXP muSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(rvonmises(n, mu, kappa));
    return rcpp_result_gen;
END_RCPP
}
// dvonmises
arma::vec dvonmises(arma::vec x, double mu, double kappa);
RcppExport SEXP _ggdmc_dvonmises(SEXP xSEXP, SEXP muSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(dvonmises(x, mu, kappa));
    return rcpp_result_gen;
END_RCPP
}
// pvonmises
arma::vec pvonmises(arma::vec q, double mu, double kappa, double tol);
RcppExport SEXP _ggdmc_pvonmises(SEXP qSEXP, SEXP muSEXP, SEXP kappaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(pvonmises(q, mu, kappa, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggdmc_dcircle", (DL_FUNC) &_ggdmc_dcircle, 7},
    {"_ggdmc_dcircle300", (DL_FUNC) &_ggdmc_dcircle300, 5},
    {"_ggdmc_rcircle", (DL_FUNC) &_ggdmc_rcircle, 5},
    {"_ggdmc_rcircle_process", (DL_FUNC) &_ggdmc_rcircle_process, 3},
    {"_ggdmc_r1d", (DL_FUNC) &_ggdmc_r1d, 3},
    {"_ggdmc_likelihood", (DL_FUNC) &_ggdmc_likelihood, 4},
    {"_ggdmc_p_df", (DL_FUNC) &_ggdmc_p_df, 13},
    {"_ggdmc_ac_", (DL_FUNC) &_ggdmc_ac_, 2},
    {"_ggdmc_trial_loglik", (DL_FUNC) &_ggdmc_trial_loglik, 2},
    {"_ggdmc_r_fastdm", (DL_FUNC) &_ggdmc_r_fastdm, 4},
    {"_ggdmc_p_fastdm", (DL_FUNC) &_ggdmc_p_fastdm, 5},
    {"_ggdmc_prd", (DL_FUNC) &_ggdmc_prd, 4},
    {"_ggdmc_init_new", (DL_FUNC) &_ggdmc_init_new, 11},
    {"_ggdmc_init_old", (DL_FUNC) &_ggdmc_init_old, 10},
    {"_ggdmc_init_newhier", (DL_FUNC) &_ggdmc_init_newhier, 13},
    {"_ggdmc_init_oldhier", (DL_FUNC) &_ggdmc_init_oldhier, 10},
    {"_ggdmc_rlba_norm", (DL_FUNC) &_ggdmc_rlba_norm, 8},
    {"_ggdmc_rprior_mat", (DL_FUNC) &_ggdmc_rprior_mat, 2},
    {"_ggdmc_test_sumlogprior", (DL_FUNC) &_ggdmc_test_sumlogprior, 2},
    {"_ggdmc_test_dprior", (DL_FUNC) &_ggdmc_test_dprior, 2},
    {"_ggdmc_spdf", (DL_FUNC) &_ggdmc_spdf, 5},
    {"_ggdmc_dtnorm", (DL_FUNC) &_ggdmc_dtnorm, 6},
    {"_ggdmc_rtnorm", (DL_FUNC) &_ggdmc_rtnorm, 5},
    {"_ggdmc_ptnorm", (DL_FUNC) &_ggdmc_ptnorm, 7},
    {"_ggdmc_rvonmises", (DL_FUNC) &_ggdmc_rvonmises, 3},
    {"_ggdmc_dvonmises", (DL_FUNC) &_ggdmc_dvonmises, 3},
    {"_ggdmc_pvonmises", (DL_FUNC) &_ggdmc_pvonmises, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggdmc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
